# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-google-analytics-data-api:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_google_analytics_data_api/spec.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.0.3"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.0.2"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        ignored_fields:
          daily_active_users:
            - name: uuid
              bypass_reason: "fast changing data"
          weekly_active_users:
            - name: uuid
              bypass_reason: "fast changing data"
          four_weekly_active_users:
            - name: uuid
              bypass_reason: "fast changing data"
          devices:
            - name: uuid
              bypass_reason: "fast changing data"
          locations:
            - name: uuid
              bypass_reason: "fast changing data"
          pages:
            - name: uuid
              bypass_reason: "fast changing data"
          traffic_sources:
            - name: uuid
              bypass_reason: "fast changing data"
          website_overview:
            - name: uuid
              bypass_reason: "fast changing data"
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
