connector_image: airbyte/source-hubspot:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: source_hubspot/spec.yaml
  connection:
    tests:
      - config_path: secrets/config_oauth.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
      - config_path: integration_tests/invalid_config_oauth.json
        status: failed
      - config_path: integration_tests/invalid_config_wrong_title.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config_oauth.json
  basic_read:
    tests:
      - config_path: secrets/config_oauth.json
        empty_streams:
        - name: property_history
          bypass_reason: has randomly calculated records
        - name: form_submissions
          bypass_reason: unable to populate
        - name: ticket_pipelines
          bypass_reason: unable to populate
        - name: engagements_meetings
          bypass_reason: unable to populate
        - name: engagements_emails
          bypass_reason: unable to populate
        - name: engagements_calls
          bypass_reason: unable to populate
        - name: quotes
          bypass_reason: unable to populate
        timeout_seconds: 3600
        expect_records:
          path: integration_tests/expected_records.jsonl
          exact_order: yes
          extra_fields: yes
          extra_records: no
  full_refresh:
    tests:
      - config_path: secrets/config_oauth.json
        configured_catalog_path: sample_files/full_refresh_oauth_catalog.json
        ignored_fields:
          companies:
            - name: properties
              bypass_reason: "fast changing data"
            - name: hs_time_in_subscriber
              bypass_reason: "fast changing data"
          contact_lists:
            - name: properties
              bypass_reason: "fast changing data"
            - name: ilsFilterBranch
              bypass_reason: "fast changing data"
          contacts:
            - name: properties
              bypass_reason: "fast changing data"
            - name: hs_time_in_subscriber
              bypass_reason: "fast changing data"
          deals:
            - name: properties
              bypass_reason: "fast changing data"
            - name: hs_time_in_qualifiedtobuy
              bypass_reason: "fast changing data"
          tickets:
            - name: properties
              bypass_reason: "fast changing data"
            - name: hs_time_in_4
              bypass_reason: "fast changing data"
  incremental:
    tests:
      - config_path: secrets/config_oauth.json
        configured_catalog_path: sample_files/incremental_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
