# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-instagram:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "integration_tests/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          extra_fields: yes
          exact_order: yes
          extra_records: no
        empty_streams:
          - name: "media"
            bypass_reason: "Floating data"
          - name: "media_insights"
            bypass_reason: "Floating data"
          - name: "user_insights"
            bypass_reason: "Floating data"
          - name: "stories"
            bypass_reason: "Stories only live for 24 hours"
          - name: "story_insights"
            bypass_reason: "Stories only live for 24 hours, so do the insights"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        ignored_fields:
          user_insights:
            - name: email_contacts
              bypass_reason: "fast changing data"
            - name: follower_count
              bypass_reason: "fast changing data"
            - name: get_directions_clicks
              bypass_reason: "fast changing data"
            - name: impressions
              bypass_reason: "fast changing data"
            - name: phone_call_clicks
              bypass_reason: "fast changing data"
            - name: profile_views
              bypass_reason: "fast changing data"
            - name: reach
              bypass_reason: "fast changing data"
            - name: text_message_clicks
              bypass_reason: "fast changing data"
            - name: website_clicks
              bypass_reason: "fast changing data"
            - name: impressions_week
              bypass_reason: "fast changing data"
            - name: reach_week
              bypass_reason: "fast changing data"
            - name: impressions_days_28
              bypass_reason: "fast changing data"
            - name: reach_days_28
              bypass_reason: "fast changing data"
            - name: online_followers
              bypass_reason: "fast changing data"
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/incremental_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
        cursor_paths:
          user_insights: ["17841408147298757", "date"]
        # because state is complex and stores values for different accounts on one hand
        # and there's no way we can set multiple cursor paths for a single stream on the other,
        # this test should be skipped as it is false negative.
        # (we can not restrict accounts via config as well)
        skip_comprehensive_incremental_tests: true
